// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzQ9Sfl9yliIctoCSSOrmpxpjRmuemb6s',
    appId: '1:642903201509:web:d7ceeb566a6832ec13e60c',
    messagingSenderId: '642903201509',
    projectId: 'sampleenov',
    authDomain: 'sampleenov.firebaseapp.com',
    storageBucket: 'sampleenov.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXSJYc94D5bM8exuwBrZOAIEMScWMvnxo',
    appId: '1:642903201509:android:5e09efdffc12888d13e60c',
    messagingSenderId: '642903201509',
    projectId: 'sampleenov',
    storageBucket: 'sampleenov.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW6KO2euAoNdQhzm2d758qguJT0P0MlyU',
    appId: '1:642903201509:ios:ae0e74c32b0fe19013e60c',
    messagingSenderId: '642903201509',
    projectId: 'sampleenov',
    storageBucket: 'sampleenov.appspot.com',
    iosClientId: '642903201509-236prm9h7a7chlir7603bf17l072bm0n.apps.googleusercontent.com',
    iosBundleId: 'com.example.sampleFireLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW6KO2euAoNdQhzm2d758qguJT0P0MlyU',
    appId: '1:642903201509:ios:ae0e74c32b0fe19013e60c',
    messagingSenderId: '642903201509',
    projectId: 'sampleenov',
    storageBucket: 'sampleenov.appspot.com',
    iosClientId: '642903201509-236prm9h7a7chlir7603bf17l072bm0n.apps.googleusercontent.com',
    iosBundleId: 'com.example.sampleFireLogin',
  );
}
